'use client';

import Image from "next/image";
import { Pencil, Palette, Weight } from "lucide-react";
import PatternDialog from "@/components/sections/pattern-dialog";

const patterns = [
  {
    id: 1,
    name: "Cozy Cable Knit Sweater",
    difficulty: "Intermediate",
    image: "/patterns-sweater.jpg",
    tools: [
      { icon: Weight, label: "Needle Size", value: "3.5mm" },
      { icon: Weight, label: "Yarn Weight", value: "100g" },
    ],
    gauge: { icon: Pencil, label: "Gauge", value: "22 sts x 30 rows" },
    stitch: { icon: Palette, label: "Stitch", value: "Stockinette Stitch" },
    instructions:
      "Cast on 100 stitches. Knit 2 rows in garter stitch. Continue in stockinette stitch until the piece measures 10 inches. Knit 2 rows in garter stitch. Bind off.",
    finishing:
      "Weave in all ends. Block the piece to measurements. Add fringe or tassels if desired.",
  },
  {
    id: 2,
    name: "Chunky Winter Beanie",
    difficulty: "Beginner",
    image: "/patterns-beanie.jpg",
    tools: [
      { icon: Weight, label: "Needle Size", value: "6mm" },
      { icon: Weight, label: "Yarn Weight", value: "150g" },
    ],
    gauge: { icon: Pencil, label: "Gauge", value: "14 sts x 20 rows" },
    stitch: { icon: Palette, label: "Stitch", value: "Rib Stitch" },
    instructions:
      "Cast on 64 stitches. Work in 1x1 ribbing for 8 inches. Decrease evenly across rows. Bind off and seam edges.",
    finishing:
      "Sew the top closed and weave in ends. Optionally, add a pom-pom.",
  },
  {
    id: 3,
    name: "Lacy Summer Shawl",
    difficulty: "Advanced",
    image: "/patterns-shawl.avif",
    tools: [
      { icon: Weight, label: "Needle Size", value: "4mm" },
      { icon: Weight, label: "Yarn Weight", value: "200g" },
    ],
    gauge: { icon: Pencil, label: "Gauge", value: "20 sts x 24 rows" },
    stitch: { icon: Palette, label: "Stitch", value: "Lace Pattern" },
    instructions:
      "Cast on 120 stitches. Work in lace pattern with YO and K2tog until length is 60 inches. Bind off loosely.",
    finishing:
      "Block gently to open up lace. Weave in ends.",
  },
  {
    id: 4,
    name: "Knitted Plant Pot Cover",
    difficulty: "Beginner",
    image: "/patterns-potcover.jpg",
    tools: [
      { icon: Weight, label: "Needle Size", value: "5mm" },
      { icon: Weight, label: "Yarn Weight", value: "50g" },
    ],
    gauge: { icon: Pencil, label: "Gauge", value: "16 sts x 22 rows" },
    stitch: { icon: Palette, label: "Stitch", value: "Seed Stitch" },
    instructions:
      "Cast on 40 stitches. Work in seed stitch for 6 inches. Bind off. Sew side edges to form a cylinder.",
    finishing:
      "Slip over pot, stretch to fit snugly. Weave in ends.",
  },
];

export default function MyPatternsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground">
      <div className="flex-1 px-4 py-6 sm:px-6 md:px-8 max-w-7xl mx-auto w-full">
        <h2 className="text-3xl md:text-4xl font-bold mb-2">Patterns</h2>
        <p className="text-muted-foreground mb-8 text-base md:text-lg max-w-2xl">
          Explore the creativity of our community with these stunning knitted pieces, each crafted from patterns generated by KnitGPT.
        </p>

        <div
          className="grid gap-6 sm:gap-8"
          style={{ gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))" }}
        >
          {patterns.map((pattern, i) => (
            <div
              key={pattern.id}
              className="bg-card rounded-2xl shadow-md hover:shadow-lg transition-shadow flex flex-col overflow-hidden"
            >
              <Image
                src={pattern.image}
                alt={pattern.name}
                width={300}
                height={200}
                className="w-full h-[180px] object-cover border-b border-border"
              />
              <div className="p-4 flex flex-col gap-2 flex-1">
                <div className="text-xs text-muted-foreground">Pattern #{i + 1}</div>
                <div className="font-semibold text-base truncate">{pattern.name}</div>
                <div className="text-sm text-muted-foreground">
                  Difficulty: {pattern.difficulty}
                </div>
                <div className="mt-auto">
                  <PatternDialog pattern={pattern} />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}