import Image from "next/image";
import Link from "next/link";
import { Home, Sparkles, Image as GalleryIcon, User } from "lucide-react";

const galleryItems = [
  { id: 1, title: "Cozy Winter Scarf", subtitle: "Pattern by KnitGenius", image: "/gallery-cardigan.jpg" },
  { id: 2, title: "Elegant Lace Shawl", subtitle: "Pattern by KnitGenius", image: "/gallery-beanie.jpg" },
  { id: 3, title: "Chunky Knit Beanie", subtitle: "Pattern by KnitGenius", image: "/gallery-sweater.webp" },
  { id: 4, title: "Fair Isle Sweater", subtitle: "Pattern by KnitGenius", image: "/gallery-shawl.jpg" },
  { id: 5, title: "Cable Knit Cardigan", subtitle: "Pattern by KnitGenius", image: "/gallery-scarf.jpg" },
];

export default function GalleryPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground">
      {/* Content */}
      <div className="flex-1 w-full px-4 md:px-8 py-10">
        <div className="max-w-screen-xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-bold mb-2">Gallery</h2>
          <p className="text-muted-foreground mb-8 text-base md:text-lg max-w-2xl">
            Explore the creativity of our community with these stunning knitted pieces, each crafted from patterns generated by KnitGPT.
          </p>

          {/* Fluid Grid with better spacing */}
          <div className="grid gap-6 sm:gap-8 grid-cols-[repeat(auto-fit,minmax(220px,1fr))]">
            {galleryItems.map((item) => (
              <div
                key={item.id}
                className="bg-card rounded-2xl overflow-hidden shadow-sm border border-border hover:shadow-md transition-shadow p-2"
              >
                <div className="relative w-full rounded-xl overflow-hidden aspect-[4/3]">
                  <Image
                    src={item.image}
                    alt={item.title}
                    fill
                    className="object-cover rounded-xl"
                    sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 25vw"
                  />
                </div>
                <div className="p-3">
                  <div className="font-semibold text-base mb-1 truncate">{item.title}</div>
                  <div className="text-sm text-muted-foreground truncate">{item.subtitle}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
